#!/usr/bin/env python
# author: exe1099

import argparse
import shutil
from pathlib import Path
import os


bookmark_file = "/home/exe/Backups/LINKED/Okular/bookmarks.xml"


### parsing command-line arguments ###
parser = argparse.ArgumentParser(description="Rename file and substitue paths in okular's "
    "bookmark-file accordingly to preserve bookmarks. Navigate to directory and provide "
    "old filename and new filename as arguments."

parser.add_argument("old", help="The current name of the file or directory.")
parser.add_argument("new", help="blabla")
inputs = parser.parse_args()
current_dir = os.getenv("PWD")
# check if old is absolute or relative
if inputs.old[0] == "/":
    old_path = Path(inputs.old)
else:
    old_path = Path(current_dir, inputs.old)


### checking for multiple sources of errors ###

# 'Cloud/' shouldn't be in path, because softlinks to Cloud-subdirectories are used
# (should be in home directory)
if "Cloud" in str(old_path):
    print(
        "You're inside 'Coud/', which shouldn't be the case. "
        "Please access from softlinks in home directory."
    )
    quit()
if "Cloud" in inputs.new:
    print("Not good. Don't use Cloud in new path.")
    quit()

# ../ for parent-directory shouldn't be in path, not implemented yet
if "../" in (str(old_path) + inputs.new):
    print("../ for parent-directory not implemented yet. Please use absolute path.")
    quit()


# check if old path even in bookmarks file
# content = list()
# with open(bookmark_file) as file:
#     for line in file.readlines():
#         content.append(line)
# for line in content:
#     if old_path in line:
#         break
# else:
#     print(
#         "Old path not contained in bookmarks file. "
#         "Check if pdf contains bookmarks, if not, it's save to rename manual."
#     )
#     quit()


### moving and replacing ###
new_path = Path(shutil.move(inputs.old, inputs.new))
if str(new_path)[0] == "/":
    pass
else:
    new_path = Path(current_dir, new_path)

print(f"Old: {old_path}")
print(f"New: {new_path}")

