#!/usr/bin/env python
# author: exe1099

import xml.etree.ElementTree as ET
import os
from pathlib import Path
import argparse

# command-line
parser = argparse.ArgumentParser(
    description="Check paths in bookmark-file for existing files."
)

# xml parser
tree = ET.parse("/home/exe/Backups/LINKED/Okular/bookmarks.xml")
root = tree.getroot()

i = 0
for document in root:
    i += 1
    # select file paths
    path = Path(document[0].text)
    if not path.is_file():
        print(f"File doesn't exist: {path}")
print(f"Checked {i} files!")
