#!/bin/bash
# $1: file to be converted
# author: exe1099


if [ $# -ne 1 ]
then
    echo "Too many parameters."
    exit 1
fi

filename=$(echo $1 | cut -d "." -f1)

filenamewithext=$filename.pdf
pandoc -o $filenamewithext $1
