#!/bin/sh

# check if dmenu already running
pgrep -x dmenu && exit


get_mount() {
    # check if drive got selected
    [ -z "$chosen" ] && exit 1
    # select mount point; listing specified dirs in beginning
    mp="$(find $1 | dmenu -i -p "Type in mount point:")"
    # check for empty input
    [ -z "$mp" ] && exit 1
    # if dir non existing, ask for make dir; run as sudo if needed
    if [ ! -d "$mp" ]; then
        mkdir_yn=$(printf "No\\nYes" | dmenu -i -p "$mp doe not exist. Create it?")
        [ "$mkdir_yn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
    fi
}


mount_usb() {
    chosen="$(echo "$usb_drives" | dmenu -p "Mount which drive?" | awk '{print $1}')"
    # try mount without mount point; doesn't work if drive not in fstab
    # sudo -A mount "$chosen" && notify-send "$chosen mounted." && exit 0
    # get mount point and mount
    # get_mount "$HOME/Devices -maxdepth 1 -type d"
    mp=$(printf "Cruzer\\nSDCard" | dmenu -i -p "Mount to ~/Devices/?")
    pmount "$chosen" "$mp" && notify-send "$chosen mounted to ~/Devices/$mp"
}


mount_android() {
    # choose drive and select drive number (e.g. from "1: Samsung Galaxy")
    chosen=$(echo "$android_drives" | dmenu -p "Which Android device?" | cut -d : -f 1)
    # get mount point
    get_mount "$HOME/Devices -maxdepth 1 -type d"
    # mount
    simple-mtpfs --device "$chosen" "$mp"
    notify-send "Android deivce mounted to $mp."
}


ask_type() {
    case $(printf "USB\\nAndroid" | dmenu -i -p "Mount a USB drive or Android device?") in
        USB) mount_usb ;;
        Android) mount_android ;;
    esac
}


android_drives=$(simple-mtpfs -l 2>/dev/null)
usb_drives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

if [ -z "$usb_drives" ]; then
    [ -z "$android_drives" ] && echo "Nothing detected" && exit
    echo "Android device(s) found."
    mount_android
else
    if [ -z "$android_drives" ]; then
        echo "USB drive(s) detected."
        mount_usb
    else
        echo "Mountable USB drive(s) and Android device(s) detected."
        ask_type
    fi
fi
