#!/bin/sh


# check if dmenu already running
pgrep -x dmenu && exit


unmount_usb() {
    [ -z "$drives" ] && exit
    chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
    [ -z "$chosen" ] && exit
    pumount "$chosen" && pgrep -x dunst && notify-send "$chosen unmounted."
}


unmount_android() {
    chosen=$(awk '/simple-mtpfs/ {print $2}' /etc/mtab | dmenu -i -p "Unmount which device?")
    [ -z "$chosen" ] && exit
    fusermount -u "$chosen" && pgrep -x dunst && notify-send "$chosen unmounted."
}


ask_type() {
        case $(printf "USB\\nAndroid" | dmenu -i -p "Unmount a USB drive or Android device?") in
        USB) unmount_usb ;;
        Android) unmount_android ;;
    esac
}


drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')

if ! grep simple-mtpfs /etc/mtab; then
    [ -z "$drives" ] && echo "No drives to unmount." && exit
    echo "Unmountable USB drive detected."
    unmount_usb
else
    if [ -z "$drives" ]
    then
        echo "Unmountable Android device detected."
        unmount_android
    else
        echo "Unmountable USB drive(s) and Android device(s) detected."
        ask_type
    fi
fi
