#!/bin/bash
# author: exe1099
# Change monitor's brightness.
# $1=1/-1: increase/decrease brightness
#
# this script must have write access to file brightness
# done by adding both to group video
# keep file brightness in video group by adding following udev-rules in /etc/udev/rules.d/backlight.rules:
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
# ACTION=="add", SUBSYSTEM=="backlight", KERNEL=="intel_backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

current_val=$(cat /sys/class/backlight/intel_backlight/brightness)
max_val=$(cat /sys/class/backlight/intel_backlight/max_brightness)
step=$(( $max_val / 16))

[ $1 -eq -1 ] && step=$((-step))

new_val=$((current_val + step))

[ $new_val -le 50 ] && new_val=50
[ $new_val -gt $max_val ] && new_val=$max_val
echo $new_val

echo $new_val > /sys/class/backlight/intel_backlight/brightness
