#!/bin/sh
# dependencies: pacman -S xorg-xrandr

chosen=$(printf "internal\\nexternal\\nmanual" | dmenu -fn "Hack Nerd Font-13" -i -p "Select display output:")
echo $chosen

case "$chosen" in
    "internal") xrandr --output eDP-1 --auto --output DP-3 --off;;
    "external") xrandr --output DP-3 --auto --output eDP-1 --off;;
    "manual") arandr
esac

~/.fehbg
