#!/bin/bash
# author: exe1099
# $1: dir in wallpapers directory to use


wp_path=/home/exe/Photos/Wallpapers/$1
image=$(ls $wp_path | grep -E '(jpg|png)$' | sort -R | tail -1)
cp $wp_path/$image ~/.background_image.jpg

feh --bg-max ~/.background_image.jpg
